export interface KeyEveningSale {
  eventId: string;
  house: 'christies' | 'sothebys';
  title: string;
  date: string;
  dateSort: string;
  location: string;
  href: string;
  kind: 'live';
  status: 'confirmed' | 'tbd_day';
}

export const keyEveningSales2026: KeyEveningSale[] = [
  {
    eventId: '2026-SBY-LON-MC-0304',
    house: 'sothebys',
    title: 'Modern & Contemporary Evening Auction',
    date: '4 Mar',
    dateSort: '2026-03-04',
    location: 'London',
    href: 'https://www.sothebys.com/en/auction-catalogue/2026/modern-contemporary-evening-auction-l26002',
    kind: 'live',
    status: 'confirmed',
  },
  {
    eventId: '2026-CHR-HK-2021-0327',
    house: 'christies',
    title: '20th/21st Century Evening Sale',
    date: '27 Mar',
    dateSort: '2026-03-27',
    location: 'Hong Kong',
    href: 'https://www.christies.com/en/auction/20th-21st-century-art-evening-sale-31240/overview',
    kind: 'live',
    status: 'confirmed',
  },
  {
    eventId: '2026-SBY-PAR-MC-0416',
    house: 'sothebys',
    title: 'Art Moderne et Contemporain Evening Auction',
    date: '16 Apr',
    dateSort: '2026-04-16',
    location: 'Paris',
    href: 'https://www.sothebys.com/en/buy/auction/2026/art-moderne-et-contemporain-evening-auction-pf2606?locale=en',
    kind: 'live',
    status: 'confirmed',
  },
  {
    eventId: '2026-SBY-NY-NOW-0514',
    house: 'sothebys',
    title: 'The Now & Contemporary Evening Auction',
    date: '14 May',
    dateSort: '2026-05-14',
    location: 'New York',
    href: 'https://www.sothebys.com/en/buy/auction/2026/the-now-contemporary-evening-auction',
    kind: 'live',
    status: 'confirmed',
  },
  {
    eventId: '2026-SBY-NY-MOD-0519',
    house: 'sothebys',
    title: 'Modern Evening Auction',
    date: '19 May',
    dateSort: '2026-05-19',
    location: 'New York',
    href: 'https://www.sothebys.com/buy/c11be70d-5448-4ef7-bdbe-254023b9b984',
    kind: 'live',
    status: 'confirmed',
  },
  {
    eventId: '2026-CHR-NY-20TH-05XX',
    house: 'christies',
    title: '20th Century Evening Sale',
    date: 'May (TBD)',
    dateSort: '2026-05-01',
    location: 'New York',
    href: 'https://www.christies.com',
    kind: 'live',
    status: 'tbd_day',
  },
  {
    eventId: '2026-CHR-NY-21ST-05XX',
    house: 'christies',
    title: '21st Century Evening Sale',
    date: 'May (TBD)',
    dateSort: '2026-05-01',
    location: 'New York',
    href: 'https://www.christies.com',
    kind: 'live',
    status: 'tbd_day',
  },
  {
    eventId: '2026-SBY-LON-MC-0624',
    house: 'sothebys',
    title: 'Modern & Contemporary Evening Auction',
    date: '24 Jun',
    dateSort: '2026-06-24',
    location: 'London',
    href: 'https://www.sothebys.com/en/buy/auction/2026/modern-contemporary-evening-auction-l26006',
    kind: 'live',
    status: 'confirmed',
  },
  {
    eventId: '2026-CHR-LON-2021-10XX',
    house: 'christies',
    title: '20/21 London Evening Sales',
    date: 'Oct (TBD)',
    dateSort: '2026-10-01',
    location: 'London',
    href: 'https://www.christies.com',
    kind: 'live',
    status: 'tbd_day',
  },
  {
    eventId: '2026-CHR-NY-20TH-11XX',
    house: 'christies',
    title: '20th Century Evening Sale',
    date: 'Nov (TBD)',
    dateSort: '2026-11-01',
    location: 'New York',
    href: 'https://www.christies.com',
    kind: 'live',
    status: 'tbd_day',
  },
  {
    eventId: '2026-CHR-NY-21ST-11XX',
    house: 'christies',
    title: '21st Century Evening Sale',
    date: 'Nov (TBD)',
    dateSort: '2026-11-01',
    location: 'New York',
    href: 'https://www.christies.com',
    kind: 'live',
    status: 'tbd_day',
  },
];
